######################################################################
# Automatically generated by qmake (2.00a) Wed May 3 15:01:06 2006
######################################################################

TEMPLATE = app
TARGET = qmadjack
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt debug console link_pkgconfig
PKGCONFIG += liblo
QT -= gui

# Input
HEADERS += QMadJACK.h
SOURCES += main.cpp QMadJACK.cpp

